addons:
  apt:
    packages:
    - libnuma-dev
    - git
    - make
sudo: required
language: minimal
services: docker
env:
  global:
  - TMP=/tmp
  - CUDNN_URL="https://storage.googleapis.com/cwpearson-cudnn/cudnn-8.0-linux-x64-v6.0.tgz"
  - CUDNN_PATH=cudnn.tar.gz
  - CUDA_ROOT=$HOME/cuda
  - CUDASDK_URL="https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run"
  - CUDASDK_PATH="cudasdk.run"
  - NCCL_SRC=$HOME/nccl
  - NCCL_PREFIX=$HOME/nccl
matrix:
  include:
  - env: BUILD_TYPE=Release
  - env: BUILD_TYPE=Debug
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- travis_retry sudo apt-get -qq update
- travis_retry sudo apt-get install --no-install-suggests --no-install-recommends
  -y g++-4.9
install:
- mkdir -vp $CUDA_ROOT
- wget $CUDASDK_URL -O $CUDASDK_PATH
- chmod +x $CUDASDK_PATH
- "./$CUDASDK_PATH --silent --toolkit --toolkitpath=$CUDA_ROOT"
- echo $HOME && ls $HOME
- echo $CUDA_ROOT && ls $CUDA_ROOT
- ln -s $CUDA_ROOT/lib64/stubs/libcuda.so $CUDA_ROOT/lib64/libcuda.so
- export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$CUDA_ROOT/lib64"
- rm -v $CUDASDK_PATH
- wget $CUDNN_URL -O $CUDNN_PATH
- tar -xvf $CUDNN_PATH
- rm $CUDNN_PATH
- mv -v cuda/include/* $CUDA_ROOT/include/.
- mv -v cuda/lib64/* $CUDA_ROOT/lib64/.
- git clone https://github.com/NVIDIA/nccl.git $NCCL_SRC
- make install -C $NCCL_SRC CUDA_HOME=$CUDA_ROOT PREFIX=$NCCL_PREFIX
- mv -v $NCCL_PREFIX/include/* $CUDA_ROOT/include/.
- mv -v $NCCL_PREFIX/lib/* $CUDA_ROOT/lib64/.
script:
- cd $TRAVIS_BUILD_DIR
- echo CXX=g++-4.9 >> Makefile.config
- echo WITH_CUDA=1 >> Makefile.config
- echo WITH_CUDNN=1 >> Makefile.config
- echo WITH_CUBLAS=1 >> Makefile.config
- echo WITH_NCCL=1 >> Makefile.config
- echo CUDA_ROOT=$CUDA_ROOT >> Makefile.config
- echo BUILD_TYPE=$BUILD_TYPE >> Makefile.config
- cd $TRAVIS_BUILD_DIR
- git status --porcelain
- make
- make docker_docs
after_success:
- export DEPLOY=dist/amd64
- export LATEST=$DEPLOY/latest
- mkdir -pv $LATEST
- cp -v lib/libheteroprof.so $LATEST/libheteroprof.so
- cp -v env.sh $LATEST/env.sh
- cp -v $TRAVIS_BUILD_DIR/docs/latex/refman.pdf $LATEST/heteroprof.pdf
- export COMMIT=$DEPLOY/$TRAVIS_COMMIT
- mkdir -pv $COMMIT
- cp -rv $LATEST/* $COMMIT/.
- export BRANCH=$DEPLOY/$TRAVIS_BRANCH
- mkdir -pv $BRANCH
- cp -rv $LATEST/* $BRANCH/.
deploy:
  provider: gcs
  access_key_id: GOOGEQY5LDVKHTFZ6AQJ
  secret_access_key:
    secure: GqfLvNr4SHxcTtNsyPK73B7jhBfTXNg/HTtXA/T8lUah4NUvYdY0uNggSUwd9SwBxf1BOLm4HclNHtbfBSxs03yGKXwbfX1lUfLfky91juQtpnrMppTOVNk9KKVs2u65AGoIMYNq9V0EjcaZQvWbTdL/k4F+MyCk7+Hw30Zhwtkag5SCpR9lrsVGqOirwmxkYvnm9twCgPNiV/4F6Z9NeZMCn157qw1M0EwknygDaRfVUuvFbvTo+3Dz+lFkrjM/Z6cfevgmJBATL2TZtGny8JHY3IWKV7jVyyKcR08eh4ylFJbr/WSGILCRrntqP58OPhd+qpBMfX6T3rfizengvJDvQhgsznVENrB1BaX8x25oyjxAcSZ/H4oOBdU8w/QpvNPhFU5hfQvDB0iabKNYy9/c7nmlVKNI41/Vkjqx4gyZRTjDA1RFIS76914v4MUH/wyd12bUXizSKjwTY1gGw9EA03JSEBMNH7XR05DmJgS/laIPi0o4BrU0f5qFWyhmbyyjW7z4oi0PCTABeBRpgkh5+Gm4YCn+tx62UPhq0yk4GfYlm7MozqkosuQPrHsZgJdJNlgHV4OXedpiS4eMcqYPj1LLrY0VTAJU7g0BIeiTjLrIjW49UxnR5m5JIO7www8KqWzZCPBYsZI4+KLJvsaTMNGwKpH8Oq7fZ58uZJE=
  bucket: cwpearson-heteroprof
  skip_cleanup: true
  local_dir: "$DEPLOY"
  on:
    all_branches: true
    condition: "$BUILD_TYPE = Release"
