addons:
  apt:
    packages:
    - libnuma-dev
    - git
    - make
sudo: required
services: docker
env:
  global:
  - TMP=/tmp
  - CUDNN_URL="https://storage.googleapis.com/cwpearson-cudnn/cudnn-8.0-linux-x64-v6.0.tgz"
  - CUDNN_PATH=cudnn.tar.gz
  - CUDA_ROOT=$HOME/cuda
  - CUDASDK_URL="https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run"
  - CUDASDK_PATH="cudasdk.run"
  - NCCL_SRC=$HOME/nccl
  - NCCL_PREFIX=$HOME/nccl
  
matrix:
  include:
    - env: BUILD_TYPE=Release
    - env: BUILD_TYPE=Debug

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- travis_retry sudo apt-get -qq update
- travis_retry sudo apt-get install --no-install-suggests --no-install-recommends -y g++-4.9
install:
- mkdir -vp $CUDA_ROOT
- wget $CUDASDK_URL -O $CUDASDK_PATH
- chmod +x $CUDASDK_PATH
- "./$CUDASDK_PATH --silent --toolkit --toolkitpath=$CUDA_ROOT"
- echo $HOME && ls $HOME
- echo $CUDA_ROOT && ls $CUDA_ROOT
- ln -s $CUDA_ROOT/lib64/stubs/libcuda.so $CUDA_ROOT/lib64/libcuda.so
- export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$CUDA_ROOT/lib64"
- rm -v $CUDASDK_PATH
- wget $CUDNN_URL -O $CUDNN_PATH
- tar -xvf $CUDNN_PATH
- mv -v cuda/include/* $CUDA_ROOT/include/.
- mv -v cuda/lib64/* $CUDA_ROOT/lib64/.
- git clone https://github.com/NVIDIA/nccl.git $NCCL_SRC
- make install -C $NCCL_SRC CUDA_HOME=$CUDA_ROOT PREFIX=$NCCL_PREFIX
- mv -v $NCCL_PREFIX/include/* $CUDA_ROOT/include/.
- mv -v $NCCL_PREFIX/lib/* $CUDA_ROOT/lib64/.
script:
- cd $TRAVIS_BUILD_DIR
- echo CXX=g++-4.9 >> Makefile.config
- echo CUDA_ROOT=$CUDA_ROOT >> Makefile.config
- echo BUILD_TYPE=$BUILD_TYPE >> Makefile.config
- cd $TRAVIS_BUILD_DIR
- make
- make docker_docs
after_success:
- export DEPLOY=dist/amd64
- export LATEST=$DEPLOY/latest
- mkdir -pv $LATEST
- cp -v lib/libheteroprof.so $LATEST/libheteroprof.so
- cp -v env.sh $LATEST/env.sh
- cp -v $TRAVIS_BUILD_DIR/docs/latex/refman.pdf $LATEST/heteroprof.pdf
- export COMMIT=$DEPLOY/$TRAVIS_COMMIT
- mkdir -pv $COMMIT
- cp -rv $LATEST/* $COMMIT/.
- export BRANCH=$DEPLOY/$TRAVIS_BRANCH
- mkdir -pv $BRANCH
- cp -rv $LATEST/* $BRANCH/.

deploy:
  provider: gcs
  access_key_id: GOOGEQY5LDVKHTFZ6AQJ
  secret_access_key:
    secure: PlTpBD2n9702BjgwHkYWpIu51SLcr0ru5Rfba9eSV10175gdB45H3Y5sslwGuyX3ihTDsR4i28kp9eiFLuLajzG22ndtT/MjjLJlsOUcdroF4z3HkZqklncbjH+18x6yxc1uTWsxEMl3gFjpVaBsMviPdVTkK9WBzcPmydpQYD91QX3woJmYMc5O6DYfkvDYk3s6T2rnb8M71Hi88RzLayMGpETYfSEZzlhEhO7T3nm/pN1CwpAEjjKLCvIQF1+h6Klz6f+eloQPbbnTICwlkfyVVgBtpuZuXtsUZbpH+zvE2+7xRaauxpMxR+jSQrDUlEdzG+sY6uLqwgjR9IBiPGDGvtI2sHCyP893VQKS/5tcYorKr3ZGFJ9KDdsJw7YlJ0n4JklJnN+MJ5sCLYXmA3+deFZ9G9WTJ3umB/vLGAuITnE6Q5qTvC7E8Ou9/6fWYYZfXWngSRBY0i32nAffMDZ6hHkYJokIwDhFMgUHjbNKIwqZyOVD9TDBj8bXiZcTDgg9lcglpPb2BKdYBwEtntLnIEo7HrNAvtsZYYrz8s8u6Hxag+6d8Etj7BMaOoXhtO5lQ+y51Yn+2VtK5KCH0Y6pftZLCg2CrVPp0biEZ/iBoGgZq4PHf1FpiNyQIR81D/EFTMVgiIDmoQ+RfrUrLp5awHGYI9R0jl3uOEAvg7g=
  bucket: cwpearson-heteroprof
  skip_cleanup: true
  local_dir: $DEPLOY
  on:
    all_branches: true
    condition: $BUILD_TYPE = Release
